const { spawn } = require('child_process');
const path = require('path');
const fs = require('fs');

/**
 * Auto-generated Startup Handler for gs-orchestrator
 * Generated by @gs/orchestrator-client
 */
function main() {
  console.log('🚀 [startupHandler] Starting services for gs-orchestrator...');
  const processes = [];

  const cleanup = () => {
    console.log('\n🛑 [startupHandler] Shutting down spawned services...');
    processes.forEach((p) => {
      try { p.kill('SIGTERM'); } catch (e) {}
    });
    process.exit(0);
  };

  process.on('SIGINT', cleanup);
  process.on('SIGTERM', cleanup);

  // GS-Orchestrator Server
  const orchestratorPath = path.join(__dirname, 'GS-Orchestrator', 'src', 'server.ts');
  const configDir = path.join(__dirname, 'config');
  console.log('⏳ Starting GS-Orchestrator server on port 9000...');
  const orchestratorProc = spawn('npx', ['--yes', 'ts-node', orchestratorPath], {
    cwd: path.dirname(orchestratorPath),
    stdio: 'inherit',
    shell: true,
    env: { ...process.env, GSSHOPPER_CONFIG_DIR: configDir },
  });
  processes.push(orchestratorProc);
  console.log('✅ GS-Orchestrator server spawned.');

  // Frontend Service (angular)
  console.log('⏳ Starting Angular frontend (npm run dev)...');
  const frontendProc = spawn('npm', ['run', 'dev'], {
    cwd: path.join(__dirname, 'GS-Orchestrator-GUI'),
    stdio: 'inherit',
    shell: true,
  });
  processes.push(frontendProc);
  console.log('✅ Frontend process spawned.');
}

main();
