const { spawn } = require('child_process');
const path = require('path');
const fs = require('fs');

/**
 * Auto-generated Startup Handler Class for gs-orchestrator
 * Implements IStartupHandler (start, stop, getStatus)
 * Generated by @gs/orchestrator-client
 */
class StartupHandler {
  constructor() {
    this.processes = [];
  }

  async start() {
    console.log('🚀 [StartupHandler] Starting services for gs-orchestrator...');
    const processes = this.processes;

    // GS-Orchestrator Server
    const orchestratorPath = path.join(__dirname, 'GS-Orchestrator', 'dist', 'server.js');
    const configDir = path.join(__dirname, 'config');
    console.log('⏳ Starting GS-Orchestrator server on port 9000...');
    const orchestratorProc = spawn('node', [orchestratorPath], {
      cwd: path.dirname(orchestratorPath),
      stdio: 'inherit',
      shell: true,
      env: { ...process.env, GSSHOPPER_CONFIG_DIR: configDir },
    });
    processes.push(orchestratorProc);
    console.log('✅ GS-Orchestrator server spawned.');

    // Frontend Service (angular)
    console.log('⏳ Starting Angular frontend (npm run dev)...');
    const frontendProc = spawn('npm', ['run', 'dev'], {
      cwd: path.join(__dirname, 'GS-Orchestrator-GUI'),
      stdio: 'inherit',
      shell: true,
    });
    processes.push(frontendProc);
    console.log('✅ Frontend process spawned.');
  }

  async stop() {
    console.log('\n🛑 [StartupHandler] Shutting down spawned services...');
    this.processes.forEach((p) => {
      try { p.kill('SIGTERM'); } catch (e) {}
    });
    this.processes = [];
  }

  async getStatus() {
    return {
      activeProcesses: this.processes.length,
    };
  }
}

const instance = new StartupHandler();

// Allow CLI direct execution
if (require.main === module) {
  const cleanup = () => {
    instance.stop().then(() => process.exit(0));
  };
  process.on('SIGINT', cleanup);
  process.on('SIGTERM', cleanup);
  instance.start();
}

module.exports = {
  StartupHandler,
  default: instance,
  startupHandler: instance,
};
