const { spawn } = require('child_process');
const path = require('path');
const fs = require('fs');

/**
 * Auto-generated Startup Handler for GS-Orchestrator
 * Generated by @gs/orchestrator-client
 */
function main() {
  console.log('🚀 [startupHandler] Starting services for GS-Orchestrator...');

  // GS-Orchestrator Server
  const orchestratorPath = path.join(__dirname, 'GS-Orchestrator', 'src', 'server.ts');
  console.log('⏳ Starting GS-Orchestrator server on port 9000...');
  const orchestratorProc = spawn('npx', ['--yes', 'ts-node', orchestratorPath], {
    cwd: path.dirname(orchestratorPath),
    stdio: 'inherit',
    shell: true,
    detached: true,
  });
  orchestratorProc.unref();
  console.log('✅ GS-Orchestrator server spawned.');
}

main();
