const { spawn } = require('child_process');
const path = require('path');
const fs = require('fs');

/**
 * Auto-generated Startup Handler for gs-orchestrator
 * Generated by @gs/orchestrator-client
 */
function main() {
  console.log('🚀 [startupHandler] Starting services for gs-orchestrator...');

  // Backend Service (TypeScript)
  const backendPath = path.join(__dirname, 'src', 'server.ts');
  const configDir = path.join(__dirname, '..', 'config');
  console.log('⏳ Starting Backend service (ts-node)...');
  const backendProc = spawn('npx', ['--yes', 'ts-node', backendPath], {
    cwd: path.dirname(backendPath),
    stdio: 'inherit',
    shell: true,
    detached: true,
    env: { ...process.env, GSSHOPPER_CONFIG_DIR: configDir },
  });
  backendProc.unref();
  console.log('✅ Backend process spawned.');
}

main();
