#!/bin/sh
set -eu

PROCESS_SERVER_URL="${PROCESS_SERVER_URL:-http://localhost:9999}"
INSTALLER_TMP="$(mktemp)"
trap 'rm -f "$INSTALLER_TMP"' EXIT

curl -fsS "$PROCESS_SERVER_URL/install.js" -o "$INSTALLER_TMP"
PROCESS_SERVER_URL="$PROCESS_SERVER_URL" node "$INSTALLER_TMP"
